### PR TITLE
Some code quality updates.

### PR DESCRIPTION
**Pull request by DomtronVox**
Hi, 
I'm working on doing some updates to the quests mod. Since the original author doesn't seems to be around and you already did some updates I thought I'd make a pull request to your repository.

I can split it up if you want, but all these commits are pretty similar.

I made no changes to the api or core functionality.

To summarize my changes: 
* I moved all the files related to integrating with optional mods to their own folder for code cleanliness. In the process I tweaked how central message is included to be a bit more consistent with the others.
* I updated the translation bits of code to use the minetest API instead of the old translation mod.
* I fixed the quest info page so the textarea is read only.

I only tested on minetest 5.2.2, but my changes should work with whatever version had the built in translation API functions added.

I plan to do some more work, but some of it may break backward compatibility. I want to make it work with SFInv mod so it becomes a tab in there. I also plan to change the data saving code to use Minetest's built in stuff instead of a custom file since that seems to be frowned on now. Likely saving player specific stuff to each player's metadata and only load a player's info when they join.

Thanks.

### CODE REVIEW

**Comment by ObaniGemini** [comment]
This looks pretty much like just cleanup, do you plan on doing more stuff on this PR or do you want this merged right away ?

**Comment by Panquesito7** [comment]
> I want to make it work with `sfinv` mod

Working on it.

**Comment by DomtronVox** [comment]
@ObaniGemini  I'm fine with you going ahead with a merge. I'll just make another pull request if/when I get the other changes done.

@Panquesito7 So I should hold off changing anything else? I don't want to make edits if they are going to conflict with your stuff.

**Comment by Panquesito7** [comment]
> So I should hold off changing anything else?

No, I will create a PR; after it gets merged you can do the changes you want. 🙂
Almost done, just need to do some tweaks.

**Comment by Panquesito7** [comment]
@DomtronVox is the "Allow edits from maintainers" checkbox enabled?

**Comment by DomtronVox** [comment]
@Panquesito7 looks like it. You mean the check box in the side bar of this pull request? Says "Allow edits and access to secrets by maintainers"

**Comment by Panquesito7** [comment]
Hmm, it doesn't allow me to push to a different branch.
It seems I can only push to your `master` branch.

Is this OK for you?

**Comment by DomtronVox** [comment]
@Panquesito7 go for it. :+1:

**Comment by Panquesito7** [comment]
Done, `sfinv` support added.

**Comment by DomtronVox** [comment]
@Panquesito7 Thanks! I tested it and it works. You can merge this pull request into your repo if you want.

Do you mind if I tweak it later? (it would be a separate pull request) I was going to work on the formspec code a bit to make it a little cleaner and allow future integrations to be easier both by internal code and if someone outside wants to add support for some custom inventory mod or something. Also I was going to add it as a tab to SFInv (via sfinv.register_page), so everything feels more integrated, which requires tweaking how the quests formspec is built to allow the tabs to be shifted down so they don't overlap onto SFInv's tabs.

**Review by Panquesito7 — APPROVED** [review]
Looks fine. 👍

**Comment by BetterToAutomateTheWorld** [comment]
Happy to see this mod updated, great job guys :+1:  :)

**Pull request merged**
